import { CanvasObject } from '@/stores/canvas-store'

export interface ProfessionalTemplate {
  id: string
  name: string
  description: string
  category: string
  width: number
  height: number
  objects: CanvasObject[]
}

// Template 1: Identificação de Produto
export const identificationTemplate: ProfessionalTemplate = {
  id: 'template-identification',
  name: 'Etiqueta de Identificação',
  description: 'Etiqueta profissional para identificação de alimentos produzidos em cozinha industrial',
  category: 'industrial',
  width: 150,
  height: 100,
  objects: [
    // Fundo branco
    {
      id: 'bg-main',
      type: 'rect',
      left: 0,
      top: 0,
      width: 150,
      height: 100,
      angle: 0,
      opacity: 1,
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 1,
      locked: false,
      selectable: false,
    },
    // Título do Produto
    {
      id: 'title-product',
      type: 'text',
      left: 5,
      top: 5,
      width: 80,
      height: 12,
      angle: 0,
      opacity: 1,
      text: 'PRODUTO',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Peso
    {
      id: 'weight',
      type: 'text',
      left: 5,
      top: 18,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Peso: 250g',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Lote
    {
      id: 'lot',
      type: 'text',
      left: 5,
      top: 25,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Lote: 001',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Data Produção
    {
      id: 'production-date',
      type: 'text',
      left: 5,
      top: 32,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Produção: 01/01/2024',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Data Validade
    {
      id: 'expiry-date',
      type: 'text',
      left: 5,
      top: 39,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Validade: 08/01/2024',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Responsável
    {
      id: 'responsible',
      type: 'text',
      left: 5,
      top: 46,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Responsável: _____',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Código Interno
    {
      id: 'internal-code',
      type: 'text',
      left: 5,
      top: 53,
      width: 80,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Código: 12345',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // QR Code (placeholder)
    {
      id: 'qrcode-main',
      type: 'qrcode',
      left: 115,
      top: 5,
      width: 30,
      height: 30,
      angle: 0,
      opacity: 1,
      locked: false,
      selectable: true,
      data: { value: 'https://example.com' },
    },
    // Código de Barras (placeholder)
    {
      id: 'barcode-main',
      type: 'barcode',
      left: 115,
      top: 38,
      width: 30,
      height: 15,
      angle: 0,
      opacity: 1,
      locked: false,
      selectable: true,
      data: { value: '1234567890' },
    },
    // Empresa
    {
      id: 'company',
      type: 'text',
      left: 5,
      top: 85,
      width: 140,
      height: 10,
      angle: 0,
      opacity: 1,
      text: 'Empresa Ltda. | CNPJ: 00.000.000/0000-00',
      fontSize: 8,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
  ],
}

// Template 2: Validade (Shelf Life)
export const shelfLifeTemplate: ProfessionalTemplate = {
  id: 'template-shelflife',
  name: 'Etiqueta de Validade',
  description: 'Etiqueta para controle de validade de alimentos com design extremamente limpo',
  category: 'validade',
  width: 100,
  height: 80,
  objects: [
    {
      id: 'bg-shelflife',
      type: 'rect',
      left: 0,
      top: 0,
      width: 100,
      height: 80,
      angle: 0,
      opacity: 1,
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 1,
      locked: false,
      selectable: false,
    },
    {
      id: 'title-shelflife',
      type: 'text',
      left: 5,
      top: 5,
      width: 90,
      height: 8,
      angle: 0,
      opacity: 1,
      text: 'PRODUTO',
      fontSize: 12,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'production-date-shelflife',
      type: 'text',
      left: 5,
      top: 15,
      width: 90,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Produção: 01/01/2024 10:30',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'expiry-highlight',
      type: 'rect',
      left: 5,
      top: 23,
      width: 90,
      height: 15,
      angle: 0,
      opacity: 1,
      fill: '#ffcccc',
      stroke: '#ff0000',
      strokeWidth: 2,
      locked: false,
      selectable: true,
    },
    {
      id: 'expiry-date-shelflife',
      type: 'text',
      left: 5,
      top: 26,
      width: 90,
      height: 8,
      angle: 0,
      opacity: 1,
      text: 'VÁLIDA ATÉ: 08/01/2024',
      fontSize: 12,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'expiry-time-shelflife',
      type: 'text',
      left: 5,
      top: 35,
      width: 90,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'HORA: 23:59',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'storage-temp',
      type: 'text',
      left: 5,
      top: 43,
      width: 90,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Armazenar: 2-8°C',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'responsible-shelflife',
      type: 'text',
      left: 5,
      top: 51,
      width: 90,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Responsável: _____',
      fontSize: 8,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'print-date',
      type: 'text',
      left: 5,
      top: 72,
      width: 90,
      height: 5,
      angle: 0,
      opacity: 1,
      text: 'Impresso em: 01/01/2024',
      fontSize: 7,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
  ],
}

// Template 3: Congelamento
export const freezingTemplate: ProfessionalTemplate = {
  id: 'template-freezing',
  name: 'Etiqueta para Congelamento',
  description: 'Etiqueta para alimentos congelados com visual industrial',
  category: 'congelamento',
  width: 150,
  height: 100,
  objects: [
    {
      id: 'bg-freezing',
      type: 'rect',
      left: 0,
      top: 0,
      width: 150,
      height: 100,
      angle: 0,
      opacity: 1,
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      locked: false,
      selectable: false,
    },
    {
      id: 'title-freezing',
      type: 'text',
      left: 5,
      top: 5,
      width: 100,
      height: 10,
      angle: 0,
      opacity: 1,
      text: 'PRODUTO CONGELADO',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'product-freezing',
      type: 'text',
      left: 5,
      top: 16,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Produto: _________________',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'weight-freezing',
      type: 'text',
      left: 5,
      top: 23,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Peso: 500g',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'freezing-date',
      type: 'text',
      left: 5,
      top: 30,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Congelado: 01/01/2024',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'expiry-freezing',
      type: 'text',
      left: 5,
      top: 37,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Validade: 01/01/2025',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'temperature-freezing',
      type: 'text',
      left: 5,
      top: 44,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Temperatura: -18°C',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'lot-freezing',
      type: 'text',
      left: 5,
      top: 51,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Lote: 001',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'employee-freezing',
      type: 'text',
      left: 5,
      top: 58,
      width: 100,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Funcionário: _____',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'qrcode-freezing',
      type: 'qrcode',
      left: 115,
      top: 5,
      width: 30,
      height: 30,
      angle: 0,
      opacity: 1,
      locked: false,
      selectable: true,
      data: { value: 'https://example.com' },
    },
    {
      id: 'notes-freezing',
      type: 'text',
      left: 5,
      top: 75,
      width: 140,
      height: 18,
      angle: 0,
      opacity: 1,
      text: 'Observações: ________________________________________',
      fontSize: 8,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
  ],
}

// Template 4: Pêssego Nacional (Premium Rastreabilidade)
export const peachNationalTemplate: ProfessionalTemplate = {
  id: 'template-peach-national',
  name: 'Pêssego Nacional - Rastreabilidade',
  description: 'Etiqueta premium de rastreabilidade para frutas com design industrial',
  category: 'frutas',
  width: 200,
  height: 100,
  objects: [
    {
      id: 'bg-peach',
      type: 'rect',
      left: 0,
      top: 0,
      width: 200,
      height: 100,
      angle: 0,
      opacity: 1,
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 1,
      locked: false,
      selectable: false,
    },
    // Topo esquerdo
    {
      id: 'title-peach',
      type: 'text',
      left: 5,
      top: 3,
      width: 120,
      height: 8,
      angle: 0,
      opacity: 1,
      text: 'PÊSSEGO NACIONAL - CAT 3',
      fontSize: 12,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'weight-peach',
      type: 'text',
      left: 5,
      top: 12,
      width: 120,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'Peso Líquido: 25kg',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'lot-info-peach',
      type: 'text',
      left: 5,
      top: 19,
      width: 120,
      height: 12,
      angle: 0,
      opacity: 1,
      text: 'LOTE CONSOLIDADO: 036543651\nNF: 63541564',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'dates-line-peach',
      type: 'text',
      left: 5,
      top: 33,
      width: 120,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'FAB: 12/04/2018 | VAL: 12/05/2018',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Parte inferior esquerda
    {
      id: 'distributor-peach',
      type: 'text',
      left: 5,
      top: 50,
      width: 120,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'DISTRIBUÍDO POR',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'dist-company-peach',
      type: 'text',
      left: 5,
      top: 57,
      width: 120,
      height: 5,
      angle: 0,
      opacity: 1,
      text: 'DISTRIBUIDOR FRUTAG LTDA',
      fontSize: 8,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'dist-info-peach',
      type: 'text',
      left: 5,
      top: 62,
      width: 120,
      height: 5,
      angle: 0,
      opacity: 1,
      text: 'CNPJ: 65.135.165/0001-25 IE: 990684052',
      fontSize: 7,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'dist-city-peach',
      type: 'text',
      left: 5,
      top: 67,
      width: 120,
      height: 4,
      angle: 0,
      opacity: 1,
      text: 'LAGES - SC',
      fontSize: 7,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Topo direito - Lote grande
    {
      id: 'lot-number-peach',
      type: 'text',
      left: 140,
      top: 5,
      width: 55,
      height: 10,
      angle: 0,
      opacity: 1,
      text: '0070180001',
      fontSize: 16,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'qr-label-peach',
      type: 'text',
      left: 140,
      top: 17,
      width: 55,
      height: 8,
      angle: 0,
      opacity: 1,
      text: 'CONSULTE PELO QR-CODE OU PELO CÓDIGO NO SITE FRUTAG.COM.BR',
      fontSize: 6,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'center',
      locked: false,
      selectable: true,
    },
    {
      id: 'qrcode-peach',
      type: 'qrcode',
      left: 155,
      top: 28,
      width: 25,
      height: 25,
      angle: 0,
      opacity: 1,
      locked: false,
      selectable: true,
      data: { value: 'https://frutag.com.br/0070180001' },
    },
    // Parte inferior direita
    {
      id: 'producer-peach',
      type: 'text',
      left: 140,
      top: 56,
      width: 55,
      height: 6,
      angle: 0,
      opacity: 1,
      text: 'PRODUZIDO POR',
      fontSize: 9,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'prod-company-peach',
      type: 'text',
      left: 140,
      top: 63,
      width: 55,
      height: 5,
      angle: 0,
      opacity: 1,
      text: 'FORNECEDOR PASSO FUNDO',
      fontSize: 7,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'prod-info-peach',
      type: 'text',
      left: 140,
      top: 68,
      width: 55,
      height: 5,
      angle: 0,
      opacity: 1,
      text: 'CNPJ: 65.161.350/0001-25 IE: 5648772102232',
      fontSize: 6,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    {
      id: 'prod-city-peach',
      type: 'text',
      left: 140,
      top: 73,
      width: 55,
      height: 4,
      angle: 0,
      opacity: 1,
      text: 'PASSO FUNDO - RS',
      fontSize: 6,
      fontFamily: 'Arial',
      fontWeight: 400,
      textAlign: 'left',
      locked: false,
      selectable: true,
    },
    // Rodapé
    {
      id: 'footer-bg-peach',
      type: 'rect',
      left: 0,
      top: 83,
      width: 200,
      height: 17,
      angle: 0,
      opacity: 1,
      fill: '#000000',
      stroke: '#000000',
      strokeWidth: 0,
      locked: false,
      selectable: false,
    },
    {
      id: 'footer-text-peach',
      type: 'text',
      left: 5,
      top: 87,
      width: 190,
      height: 8,
      angle: 0,
      opacity: 1,
      text: '◄◄ PRODUTO COM ORIGEM RASTREADA ►►',
      fontSize: 11,
      fontFamily: 'Arial',
      fontWeight: 700,
      textAlign: 'center',
      fill: '#ffffff',
      locked: false,
      selectable: true,
    },
  ],
}

export const allProfessionalTemplates: ProfessionalTemplate[] = [
  identificationTemplate,
  shelfLifeTemplate,
  freezingTemplate,
  peachNationalTemplate,
]
